import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, readdirSync, rmSync, statSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import {
  generateLaunchJson, applyLaunchEdits, writeLaunchFile, parseLaunchText, launchFileFor,
  configsFromText, regenerationLoss,
} from '../src/config/writer.ts';
import { loadConfigs } from '../src/config/loader.ts';

function scratch(): string {
  return mkdtempSync(join(tmpdir(), 'baton-writer-'));
}

/** A project with both a Flutter entrypoint and an npm dev script. */
function mixedProject(): string {
  const root = scratch();
  writeFileSync(join(root, 'pubspec.yaml'), 'name: demo\ndependencies:\n  flutter:\n    sdk: flutter\n');
  mkdirSync(join(root, 'lib'));
  writeFileSync(join(root, 'lib', 'main.dart'), 'void main() {}');
  writeFileSync(join(root, 'package.json'), JSON.stringify({
    scripts: { dev: 'vite' }, devDependencies: { vite: '5.0.0' },
  }));
  return root;
}

// --- generateLaunchJson -----------------------------------------------------

test('the generated file is JSONC with the Baton header, 2-space indent and a trailing newline', () => {
  const root = mixedProject();
  const text = generateLaunchJson(root);

  assert.match(text, /^\/\/ Generated by Baton\. VS Code-compatible — edit freely\.\n/);
  assert.match(text, /^\/\/ .*\n\/\/ .*\n\{/, 'a two-line header comment block precedes the object');
  assert.ok(text.endsWith('\n'), 'must end with a newline');
  assert.match(text, /\n  "version"/, '2-space indent');
  rmSync(root, { recursive: true, force: true });
});

test('a generated launch.json round-trips through loadConfigs into the detected targets', () => {
  const root = mixedProject();
  const file = join(root, '.vscode', 'launch.json');
  writeLaunchFile(file, generateLaunchJson(root));

  const configs = loadConfigs(file, root);
  const flutter = configs.find((c) => c.kind === 'flutter')!;
  assert.ok(flutter, 'the auto-detected Flutter entrypoint must survive the round trip');
  assert.equal(flutter.name, 'flutter run');
  assert.equal(flutter.program, 'lib/main.dart');

  const script = configs.find((c) => c.kind === 'process')!;
  assert.equal(script.name, 'npm dev', 'the detected target name, so detectTargets absorbs the duplicate');
  assert.equal(script.runtimeExecutable, 'npm');
  assert.deepEqual(script.runtimeArgs, ['run', 'dev']);
  rmSync(root, { recursive: true, force: true });
});

test('the package manager in a generated config is the one the lockfile names', () => {
  const root = scratch();
  writeFileSync(join(root, 'package.json'), JSON.stringify({ scripts: { dev: 'vite' } }));
  writeFileSync(join(root, 'pnpm-lock.yaml'), '');
  const doc = JSON.parse(stripped(generateLaunchJson(root)));
  assert.equal(doc.configurations[0].runtimeExecutable, 'pnpm');
  rmSync(root, { recursive: true, force: true });
});

test('regenerating over an existing launch.json keeps the names its author chose', () => {
  const root = scratch();
  mkdirSync(join(root, '.vscode'));
  writeFileSync(join(root, '.vscode', 'launch.json'), JSON.stringify({
    version: '0.2.0',
    configurations: [
      { name: 'docs server', runtimeExecutable: 'npx', runtimeArgs: ['serve', 'docs', '-l', '7654'] },
    ],
  }));
  const doc = JSON.parse(stripped(generateLaunchJson(root)));
  const docs = doc.configurations.find((c: any) => c.name === 'docs server');
  assert.ok(docs, 'a hand-written config must not be renamed after its last argument');
  assert.equal(docs.runtimeExecutable, 'npx', 'nor have its executable replaced by the package manager');
  rmSync(root, { recursive: true, force: true });
});

test('a project with nothing detectable still generates a valid, empty skeleton', () => {
  const root = scratch();
  mkdirSync(join(root, '.git'));
  const text = generateLaunchJson(root);
  const doc = JSON.parse(stripped(text));
  assert.deepEqual(doc.configurations, []);
  rmSync(root, { recursive: true, force: true });
});

/** Strip `//` comment lines so the body can go through plain JSON.parse. */
const stripped = (text: string) =>
  text.split('\n').filter((l) => !l.trimStart().startsWith('//')).join('\n');

// --- applyLaunchEdits: comments and layout survive ---------------------------

const FIXTURE = readFileSync(new URL('./fixtures/jsonc-launch.json', import.meta.url), 'utf8');

test('editing a value leaves every comment in the file verbatim', () => {
  const edited = applyLaunchEdits(FIXTURE, [
    { path: ['configurations', 0, 'program'], value: 'lib/main_dev.dart' },
  ]);

  for (const comment of [
    '// line comment VS Code allows',
    '/* block comment */',
    '// trailing comma next',
  ]) {
    assert.ok(edited.includes(comment), `${comment} must survive the edit verbatim`);
  }
  assert.match(edited, /"program": "lib\/main_dev\.dart"/);
  assert.ok(!edited.includes('lib/main.dart'), 'the old value must be gone');
  // Untouched siblings are byte-identical, so a save is a minimal diff.
  assert.ok(edited.includes('"toolArgs": ["--flavor", "dev"]'));
  assert.ok(edited.includes('"runtimeArgs": ["serve", "docs", "-l", "7654"]'));
});

test('an edit with an undefined value deletes the key and keeps the rest intact', () => {
  const edited = applyLaunchEdits(FIXTURE, [
    { path: ['configurations', 0, 'program'], value: undefined },
  ]);
  const configs = configsFromText(edited, '/proj');
  assert.equal(configs[0].program, undefined, 'the key must be gone from the config it named');
  assert.equal(configs[1].program, 'docs/serve.js', 'and only from that one');
  assert.ok(edited.includes('// line comment VS Code allows'));
  assert.ok(edited.includes('"name": "Sim DEV"'));
});

test('several edits apply in order and the result still parses', () => {
  const edited = applyLaunchEdits(FIXTURE, [
    { path: ['configurations', 0, 'deviceId'], value: 'iPhone 17 Pro' },
    { path: ['configurations', 1, 'port'], value: 9000 },
    { path: ['configurations', 0, 'toolArgs'], value: ['--flavor', 'staging'] },
  ]);
  const { doc, errors } = parseLaunchText(edited);
  assert.deepEqual(errors, []);
  assert.equal((doc as any).configurations[0].deviceId, 'iPhone 17 Pro');
  assert.equal((doc as any).configurations[1].port, 9000);
  assert.deepEqual((doc as any).configurations[0].toolArgs, ['--flavor', 'staging']);
  assert.ok(edited.includes('/* block comment */'));
});

test('a comment-preserving edit round-trips through loadConfigs', () => {
  const root = scratch();
  const file = join(root, '.vscode', 'launch.json');
  writeLaunchFile(file, applyLaunchEdits(FIXTURE, [
    { path: ['configurations', 0, 'deviceId'], value: 'macos' },
  ]));
  const configs = loadConfigs(file, root);
  assert.equal(configs[0].deviceId, 'macos');
  assert.equal(configs[1].name, 'docs server');
  rmSync(root, { recursive: true, force: true });
});

// --- writeLaunchFile ---------------------------------------------------------

test('writing creates missing parent directories and leaves no temporary file behind', () => {
  const root = scratch();
  const file = join(root, '.vscode', 'launch.json');
  const text = generateLaunchJson(root);

  const { mtimeMs } = writeLaunchFile(file, text);
  assert.equal(readFileSync(file, 'utf8'), text);
  assert.equal(mtimeMs, statSync(file).mtimeMs);
  assert.deepEqual(readdirSync(join(root, '.vscode')), ['launch.json'], 'no .tmp sibling may survive');
  rmSync(root, { recursive: true, force: true });
});

test('invalid JSONC is refused before anything is written, naming line and column', () => {
  const root = scratch();
  const file = join(root, '.vscode', 'launch.json');
  assert.throws(
    () => writeLaunchFile(file, '{\n  "configurations": [\n    { "name": }\n  ]\n}\n'),
    /invalid JSONC: 3:\d+ /,
  );
  assert.ok(!readdirSync(root).includes('.vscode'), 'a rejected write must not create anything');
  rmSync(root, { recursive: true, force: true });
});

test('text that parses but is not a launch.json is refused, leaving the file untouched', () => {
  // Syntactically valid JSON is not the bar: `[]` and `"hi"` parse cleanly and
  // would have replaced a working file, with the write reporting success and
  // the project reporting zero configurations -- indistinguishable from a
  // project that legitimately has none.
  const root = scratch();
  const file = join(root, '.vscode', 'launch.json');
  const good = '{ "configurations": [{ "name": "keep me", "type": "dart" }] }\n';
  writeLaunchFile(file, good);

  for (const bad of ['[]', '"hi"', 'null', '42', '{ "version": "0.2.0" }',
    '{ "configurations": {} }', '{ "configurations": "nope" }']) {
    assert.throws(
      () => writeLaunchFile(file, bad),
      /not a launch\.json/,
      `${bad} must not be accepted as a launch.json`,
    );
    assert.equal(readFileSync(file, 'utf8'), good, `${bad} must not have replaced the file`);
  }
  assert.deepEqual(readdirSync(join(root, '.vscode')), ['launch.json'], 'and no temp file survives');
  rmSync(root, { recursive: true, force: true });
});

test('an empty configurations array is a legitimate launch.json', () => {
  // The skeleton `baton init` writes for a project with nothing detected yet.
  const root = scratch();
  const file = join(root, 'launch.json');
  writeLaunchFile(file, '{ "version": "0.2.0", "configurations": [] }\n');
  assert.ok(readFileSync(file, 'utf8').includes('configurations'));
  rmSync(root, { recursive: true, force: true });
});

test('an unexpected mtime is a conflict, and the file on disk is left alone', () => {
  const root = scratch();
  const file = join(root, 'launch.json');
  writeLaunchFile(file, '{ "configurations": [] }\n');
  const before = readFileSync(file, 'utf8');

  assert.throws(
    () => writeLaunchFile(file, '{ "configurations": [{ "name": "x" }] }\n', 1),
    /conflict: file changed on disk/,
  );
  assert.equal(readFileSync(file, 'utf8'), before);

  // The current mtime is accepted, and the write goes through.
  const current = statSync(file).mtimeMs;
  writeLaunchFile(file, '{ "configurations": [{ "name": "x" }] }\n', current);
  assert.match(readFileSync(file, 'utf8'), /"name": "x"/);
  rmSync(root, { recursive: true, force: true });
});

test('an expected mtime for a file that does not exist yet is not a conflict', () => {
  const root = scratch();
  const file = join(root, '.claude', 'launch.json');
  writeLaunchFile(file, '{ "configurations": [] }\n', 12345);
  assert.ok(readFileSync(file, 'utf8').includes('configurations'));
  rmSync(root, { recursive: true, force: true });
});

// --- parseLaunchText ---------------------------------------------------------

test('parseLaunchText reports line and column, not a raw offset', () => {
  const { errors } = parseLaunchText('{\n  "a": 1,\n  "b":\n}\n');
  assert.ok(errors.length > 0);
  assert.equal(typeof errors[0].line, 'number');
  assert.equal(typeof errors[0].col, 'number');
  assert.ok(errors[0].message.length > 0, 'the code must be spelled out, not printed as a number');
});

test('parseLaunchText accepts comments and trailing commas the way VS Code does', () => {
  const { doc, errors } = parseLaunchText(FIXTURE);
  assert.deepEqual(errors, []);
  assert.equal((doc as any).configurations.length, 2);
});

// --- regenerationLoss: what `baton init` would destroy -----------------------

test('regenerationLoss names every key a regenerated file would not carry back', () => {
  // The reason `baton init --force` must not run over a hand-tuned file:
  // generateLaunchJson emits only what detectTargets can see, which is a small
  // subset of what the loader reads. Everything else is silently dropped.
  const loss = regenerationLoss(configsFromText(FIXTURE, '/proj'), FIXTURE);

  const sim = loss.configs.find((c) => c.name === 'Sim DEV')!;
  assert.deepEqual(sim.keys, ['deviceId', 'toolArgs', 'args', 'env'],
    'a flutter config keeps only its name and program');
  assert.equal(sim.dropped, false);

  const docs = loss.configs.find((c) => c.name === 'docs server')!;
  assert.deepEqual(docs.keys, ['program', 'args', 'port'],
    'a process config keeps only its name, executable and runtimeArgs');

  assert.equal(loss.commentLines, 3, 'every comment in the file is lost too');
  assert.equal(loss.any, true);
});

test('regenerationLoss flags a configuration that would vanish entirely', () => {
  // detectTargets skips a non-dart config with no runtimeExecutable, so
  // regeneration does not merely strip its keys -- the whole entry disappears.
  const text = '{ "configurations": [ { "name": "orphan", "port": 3000 } ] }';
  const loss = regenerationLoss(configsFromText(text, '/proj'), text);
  assert.equal(loss.configs[0].dropped, true);
  assert.equal(loss.any, true);
});

test('regenerationLoss reports nothing for a file regeneration reproduces exactly', () => {
  const root = mixedProject();
  const text = generateLaunchJson(root);
  const loss = regenerationLoss(configsFromText(text, root), text);
  assert.deepEqual(loss.configs, [], 'a generated file round-trips, so nothing is at risk');
  assert.equal(loss.commentLines, 2, 'except the header Baton itself writes');
  assert.equal(loss.any, false, 'and its own header is not a reason to refuse');
  rmSync(root, { recursive: true, force: true });
});

// --- configsFromText: must not drift from loader.ts's normalise() ------------

test('configsFromText produces exactly what loadConfigs produces for the same bytes', () => {
  const root = scratch();
  const file = join(root, 'launch.json');
  writeFileSync(file, FIXTURE);
  const fromText = configsFromText(FIXTURE, root);

  assert.deepEqual(
    fromText,
    loadConfigs(file, root),
    'the editor must agree with what actually runs, key for key',
  );

  // A deepEqual over two configs that both leave a key undefined proves nothing
  // about that key. Pin that the fixture actually carries every field
  // `normalise()` reads, so the comparison above has something to compare.
  const carried = new Set<string>();
  for (const config of fromText) {
    for (const [key, value] of Object.entries(config)) {
      if (value !== undefined && !(Array.isArray(value) && value.length === 0)) carried.add(key);
    }
  }
  for (const key of ['name', 'kind', 'cwd', 'program', 'deviceId', 'toolArgs', 'args',
    'runtimeExecutable', 'runtimeArgs', 'port', 'env']) {
    assert.ok(carried.has(key), `the fixture must exercise ${key}, or the drift pin does not cover it`);
  }
  rmSync(root, { recursive: true, force: true });
});

test('configsFromText on unparseable or shapeless text is empty rather than a throw', () => {
  assert.deepEqual(configsFromText('{ "configurations": [ }', '/tmp'), []);
  assert.deepEqual(configsFromText('{ "version": "0.2.0" }', '/tmp'), []);
});

// --- launchFileFor -----------------------------------------------------------

test('launchFileFor prefers .vscode, falls back to .claude, and is null when neither exists', () => {
  const root = scratch();
  assert.equal(launchFileFor(root), null);

  mkdirSync(join(root, '.claude'));
  writeFileSync(join(root, '.claude', 'launch.json'), '{}');
  assert.equal(launchFileFor(root), join(root, '.claude', 'launch.json'));

  mkdirSync(join(root, '.vscode'));
  writeFileSync(join(root, '.vscode', 'launch.json'), '{}');
  assert.equal(launchFileFor(root), join(root, '.vscode', 'launch.json'));
  rmSync(root, { recursive: true, force: true });
});
