import { existsSync, mkdirSync, renameSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { randomBytes } from 'node:crypto';
import {
  applyEdits, modify, parse as parseJsonc, printParseErrorCode,
  type JSONPath, type ParseError,
} from 'jsonc-parser';
import { detectPackageManager, detectTargets, type Target } from './detect.ts';

/**
 * Writing launch.json, without destroying what the human wrote.
 *
 * `loader.ts` deliberately stays read-only: reading is on the path of every run
 * and must never be able to touch the file. Writing is the opposite -- it is
 * rare, deliberate, and has to be careful, so it lives here.
 *
 * Two rules shape everything below. The file is shared with VS Code / Cursor, so
 * an edit made from Baton has to leave comments, formatting and unrelated keys
 * exactly as they were (hence `jsonc-parser`'s `modify` rather than
 * parse-mutate-stringify). And the file is read by other processes while we
 * write it, so a write is atomic: a reader sees the old file or the new one,
 * never a half-written one.
 */

/** One position in the text, as a person reads it -- both 1-based. */
export type LaunchParseError = { line: number; col: number; message: string };

/** A single change, addressed the way `jsonc-parser` addresses nodes. */
export type LaunchEdit = { path: (string | number)[]; value: unknown };

/** VS Code's own formatting defaults, and the ones the generator emits. */
const FORMATTING = { insertSpaces: true, tabSize: 2 } as const;

const HEADER =
  '// Generated by Baton. VS Code-compatible — edit freely.\n' +
  '// Reference: https://code.visualstudio.com/docs/editor/debugging#_launch-configurations\n';

/** The launch.json a project uses, in the same order `detectTargets` reads them. */
export function launchFileFor(root: string): string | null {
  for (const rel of [join('.vscode', 'launch.json'), join('.claude', 'launch.json')]) {
    const path = join(root, rel);
    if (existsSync(path)) return path;
  }
  return null;
}

/**
 * Parse launch.json text the way VS Code does, collecting errors instead of throwing.
 *
 * Offsets are translated to line/column here: an editor pane showing the raw
 * text can point at the problem, and "3:11" is actionable where "offset 47" is
 * something the reader has to count out by hand.
 */
export function parseLaunchText(text: string): { doc: unknown; errors: LaunchParseError[] } {
  const raw: ParseError[] = [];
  const doc = parseJsonc(text, raw, { allowTrailingComma: true, disallowComments: false });
  return { doc, errors: raw.map((error) => ({ ...lineCol(text, error.offset), message: printParseErrorCode(error.error) })) };
}

function lineCol(text: string, offset: number): { line: number; col: number } {
  let line = 1;
  let col = 1;
  const stop = Math.min(offset, text.length);
  for (let i = 0; i < stop; i++) {
    if (text[i] === '\n') { line++; col = 1; } else col++;
  }
  return { line, col };
}

/**
 * A launch.json for a project that has none, built from what is already there.
 *
 * The point is that nobody has to learn the schema to get started: every target
 * Baton can already detect becomes a configuration, written in the shape
 * `loader.ts` reads back, so the generated file round-trips exactly.
 */
export function generateLaunchJson(root: string): string {
  const configurations = detectTargets(root)
    .map((target) => configurationFor(target, root))
    .filter((c): c is Record<string, unknown> => c !== undefined);

  return HEADER + JSON.stringify({ version: '0.2.0', configurations }, null, 2) + '\n';
}

function configurationFor(target: Target, root: string): Record<string, unknown> | undefined {
  if (target.kind === 'flutter') {
    // `type: dart` is the marker the Dart-Code extension uses and the one
    // `loader.ts` keys `kind: 'flutter'` off; anything else would come back as a
    // plain process and lose hot reload.
    const config: Record<string, unknown> = { name: target.name, type: 'dart', request: 'launch' };
    const program = target.config?.program;
    if (program) config.program = program;
    return config;
  }

  // A script target: `loader.ts` reads exactly `runtimeExecutable` and
  // `runtimeArgs` back, so those two keys are what has to be right.
  const args = target.args ?? [];
  if (!target.command) return undefined;

  // A detected dev script is named "npm run dev" only because that is how the
  // picker labels it; in a launch.json the script's own name reads better. A
  // config that came from an existing launch.json keeps the name its author
  // chose -- regenerating must not rename someone's configuration.
  const fromScript = target.source === 'package.json';
  return {
    name: (fromScript ? args.at(-1) : undefined) ?? target.name,
    type: 'node',
    request: 'launch',
    // Spelled out rather than assumed: a pnpm/bun project run with `npm` fails
    // in a way that looks like a broken script.
    runtimeExecutable: fromScript ? detectPackageManager(root).command : target.command,
    runtimeArgs: args,
  };
}

/**
 * Apply edits to launch.json text, preserving comments, spacing and key order.
 *
 * `value: undefined` removes the key (or the array element the path ends at).
 * Edits are applied one at a time because each one shifts the offsets the next
 * one is computed against.
 */
export function applyLaunchEdits(text: string, edits: LaunchEdit[]): string {
  let out = text;
  for (const edit of edits) {
    out = applyEdits(out, modify(out, edit.path as JSONPath, edit.value, { formattingOptions: { ...FORMATTING } }));
  }
  return out;
}

/**
 * Write launch.json safely: valid, unraced, and atomic.
 *
 * Validation comes first so a broken file is refused before it can replace a
 * working one. `expectedMtimeMs` is the optimistic-locking check -- the HUD read
 * the file, the user edited it in a textarea, and meanwhile VS Code (or another
 * HUD window) may have saved over it; overwriting silently would throw away
 * someone's work. Finally the write goes to a temporary file in the same
 * directory and is `rename`d into place, which is atomic on every platform we
 * target, so a concurrent reader never sees a partial file.
 */
export function writeLaunchFile(file: string, text: string, expectedMtimeMs?: number): { mtimeMs: number } {
  const { errors } = parseLaunchText(text);
  if (errors.length > 0) {
    const first = errors[0];
    throw new Error(`invalid JSONC: ${first.line}:${first.col} ${first.message}`);
  }

  if (expectedMtimeMs !== undefined && existsSync(file) && statSync(file).mtimeMs !== expectedMtimeMs) {
    throw new Error('conflict: file changed on disk');
  }

  const dir = dirname(file);
  mkdirSync(dir, { recursive: true });

  // Same directory as the target, so the rename stays within one filesystem;
  // a cross-device rename is not atomic and would fail outright.
  const tmp = join(dir, `.${randomBytes(6).toString('hex')}.launch.tmp`);
  try {
    writeFileSync(tmp, text, 'utf8');
    renameSync(tmp, file);
  } catch (err) {
    rmSync(tmp, { force: true });
    throw err;
  }

  return { mtimeMs: statSync(file).mtimeMs };
}
