import { existsSync, mkdirSync, renameSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { randomBytes } from 'node:crypto';
import {
  applyEdits, modify, parse as parseJsonc, printParseErrorCode,
  type JSONPath, type ParseError,
} from 'jsonc-parser';
import { detectPackageManager, detectTargets, type Target } from './detect.ts';
import type { LaunchConfig } from './loader.ts';

/**
 * Writing launch.json, without destroying what the human wrote.
 *
 * `loader.ts` deliberately stays read-only: reading is on the path of every run
 * and must never be able to touch the file. Writing is the opposite -- it is
 * rare, deliberate, and has to be careful, so it lives here.
 *
 * Two rules shape everything below. The file is shared with VS Code / Cursor, so
 * an edit made from Baton has to leave comments, formatting and unrelated keys
 * exactly as they were (hence `jsonc-parser`'s `modify` rather than
 * parse-mutate-stringify). And the file is read by other processes while we
 * write it, so a write is atomic: a reader sees the old file or the new one,
 * never a half-written one.
 */

/** One position in the text, as a person reads it -- both 1-based. */
export type LaunchParseError = { line: number; col: number; message: string };

/** A single change, addressed the way `jsonc-parser` addresses nodes. */
export type LaunchEdit = { path: (string | number)[]; value: unknown };

/** VS Code's own formatting defaults, and the ones the generator emits. */
const FORMATTING = { insertSpaces: true, tabSize: 2 } as const;

const HEADER =
  '// Generated by Baton. VS Code-compatible — edit freely.\n' +
  '// Reference: https://code.visualstudio.com/docs/editor/debugging#_launch-configurations\n';

/** The launch.json a project uses, in the same order `detectTargets` reads them. */
export function launchFileFor(root: string): string | null {
  for (const rel of [join('.vscode', 'launch.json'), join('.claude', 'launch.json')]) {
    const path = join(root, rel);
    if (existsSync(path)) return path;
  }
  return null;
}

/**
 * Parse launch.json text the way VS Code does, collecting errors instead of throwing.
 *
 * Offsets are translated to line/column here: an editor pane showing the raw
 * text can point at the problem, and "3:11" is actionable where "offset 47" is
 * something the reader has to count out by hand.
 */
export function parseLaunchText(text: string): { doc: unknown; errors: LaunchParseError[] } {
  const raw: ParseError[] = [];
  const doc = parseJsonc(text, raw, { allowTrailingComma: true, disallowComments: false });
  return { doc, errors: raw.map((error) => ({ ...lineCol(text, error.offset), message: printParseErrorCode(error.error) })) };
}

function lineCol(text: string, offset: number): { line: number; col: number } {
  let line = 1;
  let col = 1;
  const stop = Math.min(offset, text.length);
  for (let i = 0; i < stop; i++) {
    if (text[i] === '\n') { line++; col = 1; } else col++;
  }
  return { line, col };
}

/**
 * The configurations in a piece of launch.json *text*, without a file.
 *
 * The editor validates what is in the textarea, which by definition has not been
 * saved yet -- `loadConfigs` reads a path, and writing the draft to a temp file
 * on every keystroke to get it parsed would be absurd.
 *
 * This mirrors `normalise()` in `loader.ts`, which stays read-only and is the
 * authority on the shape. `test/writer.test.ts` asserts the two agree on the
 * same fixture, so a change to one that is not made here fails a test rather
 * than quietly making the editor disagree with what actually runs.
 */
export function configsFromText(text: string, cwd: string): LaunchConfig[] {
  return configEntries(text, cwd).map((entry) => entry.config);
}

/**
 * The same configurations, each with its index in the raw `configurations` array.
 *
 * The editor addresses edits by jsonc path -- `['configurations', 3, 'program']`
 * -- so it needs the index in the *file*, which is not the index in the list it
 * renders: an entry with no `name` is skipped here exactly as `loader.ts` skips
 * it, and every later index would otherwise be off by one and edit the wrong
 * configuration.
 */
export function configEntries(text: string, cwd: string): Array<{ index: number; config: LaunchConfig }> {
  const { doc } = parseLaunchText(text);
  const configurations = (doc as { configurations?: unknown } | undefined)?.configurations;
  if (!Array.isArray(configurations)) return [];

  return configurations
    .map((raw, index) => ({ raw, index }))
    .filter((entry): entry is { raw: Record<string, unknown>; index: number } =>
      Boolean(entry.raw) && typeof entry.raw === 'object' &&
      typeof (entry.raw as Record<string, unknown>).name === 'string')
    .map(({ raw, index }) => ({ index, config: {
      name: raw.name as string,
      kind: raw.type === 'dart' ? 'flutter' : 'process',
      cwd,
      program: typeof raw.program === 'string' ? raw.program : undefined,
      deviceId: typeof raw.deviceId === 'string' ? raw.deviceId : undefined,
      toolArgs: asStringArray(raw.toolArgs),
      args: asStringArray(raw.args),
      runtimeExecutable: typeof raw.runtimeExecutable === 'string' ? raw.runtimeExecutable : undefined,
      runtimeArgs: asStringArray(raw.runtimeArgs),
      port: typeof raw.port === 'number' ? raw.port : undefined,
      env: asEnv(raw.env),
    } }));
}

const asStringArray = (v: unknown): string[] =>
  Array.isArray(v) ? v.filter((x): x is string => typeof x === 'string') : [];

const asEnv = (v: unknown): Record<string, string> | undefined => {
  if (typeof v !== 'object' || v === null || Array.isArray(v)) return undefined;
  const out: Record<string, string> = {};
  for (const [key, value] of Object.entries(v as Record<string, unknown>)) {
    if (value === null || value === undefined || typeof value === 'object') continue;
    out[key] = String(value);
  }
  return out;
};

/**
 * A launch.json for a project that has none, built from what is already there.
 *
 * The point is that nobody has to learn the schema to get started: every target
 * Baton can already detect becomes a configuration, written in the shape
 * `loader.ts` reads back, so the generated file round-trips exactly.
 */
export function generateLaunchJson(root: string): string {
  const configurations = detectTargets(root)
    .map((target) => configurationFor(target, root))
    .filter((c): c is Record<string, unknown> => c !== undefined);

  return HEADER + JSON.stringify({ version: '0.2.0', configurations }, null, 2) + '\n';
}

function configurationFor(target: Target, root: string): Record<string, unknown> | undefined {
  if (target.kind === 'flutter') {
    // `type: dart` is the marker the Dart-Code extension uses and the one
    // `loader.ts` keys `kind: 'flutter'` off; anything else would come back as a
    // plain process and lose hot reload.
    const config: Record<string, unknown> = { name: target.name, type: 'dart', request: 'launch' };
    const program = target.config?.program;
    if (program) config.program = program;
    return config;
  }

  // A script target: `loader.ts` reads exactly `runtimeExecutable` and
  // `runtimeArgs` back, so those two keys are what has to be right.
  const args = target.args ?? [];
  if (!target.command) return undefined;

  // The target's own name, not the bare script name.
  //
  // `detectTargets` de-duplicates by name, so a config called "npm dev" absorbs
  // the package.json target it was generated from; one called "dev" would not,
  // and the picker would offer the same command twice. It also keeps
  // regeneration idempotent -- a second pass over a file this function wrote
  // sees the same names and produces the same file, instead of a second
  // configuration colliding with the first.
  return {
    name: target.name,
    type: 'node',
    request: 'launch',
    // Spelled out rather than assumed: a pnpm/bun project run with `npm` fails
    // in a way that looks like a broken script.
    runtimeExecutable: target.source === 'package.json' ? detectPackageManager(root).command : target.command,
    runtimeArgs: args,
  };
}

/**
 * Apply edits to launch.json text, preserving comments, spacing and key order.
 *
 * `value: undefined` removes the key (or the array element the path ends at).
 * Edits are applied one at a time because each one shifts the offsets the next
 * one is computed against.
 */
export function applyLaunchEdits(text: string, edits: LaunchEdit[]): string {
  let out = text;
  for (const edit of edits) {
    out = applyEdits(out, modify(out, edit.path as JSONPath, edit.value, { formattingOptions: { ...FORMATTING } }));
  }
  return out;
}

/**
 * Write launch.json safely: valid, unraced, and atomic.
 *
 * Validation comes first so a broken file is refused before it can replace a
 * working one. `expectedMtimeMs` is the optimistic-locking check -- the HUD read
 * the file, the user edited it in a textarea, and meanwhile VS Code (or another
 * HUD window) may have saved over it; overwriting silently would throw away
 * someone's work. Finally the write goes to a temporary file in the same
 * directory and is `rename`d into place, which is atomic on every platform we
 * target, so a concurrent reader never sees a partial file.
 */
export function writeLaunchFile(file: string, text: string, expectedMtimeMs?: number): { mtimeMs: number } {
  const { errors } = parseLaunchText(text);
  if (errors.length > 0) {
    const first = errors[0];
    throw new Error(`invalid JSONC: ${first.line}:${first.col} ${first.message}`);
  }

  if (expectedMtimeMs !== undefined && existsSync(file) && statSync(file).mtimeMs !== expectedMtimeMs) {
    throw new Error('conflict: file changed on disk');
  }

  const dir = dirname(file);
  mkdirSync(dir, { recursive: true });

  // Same directory as the target, so the rename stays within one filesystem;
  // a cross-device rename is not atomic and would fail outright.
  const tmp = join(dir, `.${randomBytes(6).toString('hex')}.launch.tmp`);
  try {
    writeFileSync(tmp, text, 'utf8');
    renameSync(tmp, file);
  } catch (err) {
    rmSync(tmp, { force: true });
    throw err;
  }

  return { mtimeMs: statSync(file).mtimeMs };
}
